# ExFat appveyor.yml script

branches:
  only:
    - master

skip_commits:
  files:
    - README.md

version: '{branch}-{build}'
image: Visual Studio 2017

install:
  - git submodule update --init --recursive
  - echo "" > ExFat.Core\Properties\ProductInfo.cs
  - echo "" > ExFat.Core\ExFat.nuspec
  - echo "" > ExFat.DiscUtils\ExFat.DiscUtils.nuspec

before_build:
  nuget restore

notifications:
  provider: Slack
  auth_token:
      secure: tv8q1S0sKJGnirkiriCf+BEXA1+EyX7TOBtHyp/hBqqpRcB0AofQt99AvR4zTRHz2Bh0XtzFKABzoMZ7bXaCWdFraIoT/52oK/+ktx85fYE=
  channel: '#build'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
  project: ExFat.sln

artifacts:
  - path: 'ExFat.Core\bin\$(configuration)\*.nupkg'
  - path: 'ExFat.DiscUtils\bin\$(configuration)\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
