SourceDisks:
- \\.\PhysicalDrive0
TargetDiskType: Vhd
TargetDiskSize: 8796093022208  # 8 TB Disk
SearchPatterns:
# Windows memory analysis
- hyberfil.sys$
- pagefile.sys$
- swapfile.sys$
# Windows Registry analysis
- system32\\.*\\sam$
- system32\\.*\\sam.log
- system32\\.*\\security$
- system32\\.*\\security.log
- system32\\.*\\software$
- system32\\.*\\software.log
- system32\\.*\\system$
- system32\\.*\\system.log
- users\\.*\\ntuser.dat$
- users\\.*\\ntuser.dat.log
# - users\\.*\\usrclass.dat$     <- part of appdata
# - users\\.*\\usrclass.dat.log  <- part of appdata
# Windows log analysis
- \.evtx$
- \\logs\\
- \.log$
# Windows user analysis
- \\users\\.*\\appdata\\
- \\users\\.*\\recent\\
- windows\\prefetch\\
- windows\\appcompat\\
- thumbs\.db$
- \$Recycle.Bin\\
