SourceDisks:
- \\.\PhysicalDrive0
TargetDiskType: Vhd
TargetDiskSize: 8796093022208
TargetPartitionType: ExFat
CopyRetryCount: 3
SearchPatterns:
# Meta Files (Win)
- (?<!\w)\$mft$
- (?<!\w)\$logfile$
- (?<!\w)\$recycle.bin[/\\]
# Memory (Win)
- (?<!\w)hyberfil\.sys$
- (?<!\w)pagefile\.sys$
- (?<!\w)swapfile\.sys$
# Registry (Win)
- (?<!\w)system32[/\\].*[/\\]sam$
- (?<!\w)system32[/\\].*[/\\]sam\.log
- (?<!\w)system32[/\\].*[/\\]security$
- (?<!\w)system32[/\\].*[/\\]security\.log
- (?<!\w)system32[/\\].*[/\\]software$
- (?<!\w)system32[/\\].*[/\\]software\.log
- (?<!\w)system32[/\\].*[/\\]system$
- (?<!\w)system32[/\\].*[/\\]system\.log
- (?<!\w)users[/\\].*[/\\]ntuser\.dat$
- (?<!\w)users[/\\].*[/\\]ntuser\.dat\.log
- (?<!\w)users[/\\].*[/\\]usrclass.dat$
- (?<!\w)users[/\\].*[/\\]usrclass.dat.log
# Events (Win)
- \.evtx$
- (?<!\w)logs[/\\]
- (?<!\w)logfiles[/\\]
- \.log$
# Events (Unix)
- (?<!\w)var[/\\]log
- (?<!\w)\.fseventsd
# User Navigation (Win)
- (?<!\w)users[/\\].*[/\\]appdata[/\\]
- (?<!\w)users[/\\].*[/\\]recent[/\\]
- (?<!\w)schedlgu\.txt$
- (?<!\w)prefetch[/\\]
- (?<!\w)inf[/\\]setupapi\.dev\.log$
- (?<!\w)appcompat[/\\]programs[/\\]
- (?<!\w)system32[/\\]drivers[/\\]etc[/\\]hosts$
- (?<!\w)system32[/\\]sru[/\\]
- (?<!\w)microsoft[/\\]search[/\\]data[/\\]applications[/\\]windows[/\\]
- (?<!\w)microsoft[/\\]windows[/\\]start\smenu[/\\]programs[/\\]startup[/\\]
- (?<!\w)thumbs\.db$
# User Navigation (Unix)
- (?<!\w)etc[/\\]hosts
- (?<!\w)system[/\\]library[/\\]startupitems
