SourceDisks:
- \\.\PhysicalDrive0
TargetDiskType: Vhd
TargetDiskSize: 1099511627776
TargetPartitionType: ExFat
CopyRetryCount: 3
SearchPatterns:
# Meta Files (Win)
- (?<!\w)\$mft$
- (?<!\w)\$logfile$
# Memory (Win)
- (?<!\w)hyberfil\.sys$
- (?<!\w)pagefile\.sys$
- (?<!\w)swapfile\.sys$
# Registry (Win)
- (?<!\w)system32[/\\].*[/\\]sam$
- (?<!\w)system32[/\\].*[/\\]sam\.log
- (?<!\w)system32[/\\].*[/\\]security$
- (?<!\w)system32[/\\].*[/\\]security\.log
- (?<!\w)system32[/\\].*[/\\]software$
- (?<!\w)system32[/\\].*[/\\]software\.log
- (?<!\w)system32[/\\].*[/\\]system$
- (?<!\w)system32[/\\].*[/\\]system\.log
- (?<!\w)users[/\\].*[/\\]ntuser\.dat$
- (?<!\w)users[/\\].*[/\\]ntuser\.dat\.log
- (?<!\w)users[/\\].*[/\\]usrclass\.dat$
- (?<!\w)users[/\\].*[/\\]usrclass\.dat\.log
# Events (Win)
- \.evtx$
- (?<!\w)logs[/\\]
- (?<!\w)logfiles[/\\]
- \.log$
# Events (Unix)
- (?<!\w)var[/\\]log
- (?<!\w)\.fseventsd
# User Behaviour (Win)
- (?<!\w)\$recycle.bin[/\\]
- (?<!\w)users[/\\].*[/\\]appdata[/\\]
- (?<!\w)users[/\\].*[/\\]recent[/\\]
- (?<!\w)schedlgu\.txt$
- (?<!\w)prefetch[/\\]
- (?<!\w)inf[/\\]setupapi\.dev\.log$
- (?<!\w)appcompat[/\\]programs[/\\]
- (?<!\w)system32[/\\]drivers[/\\]etc[/\\]hosts$
- (?<!\w)system32[/\\]sru[/\\]
- (?<!\w)microsoft[/\\]search[/\\]data[/\\]applications[/\\]windows[/\\]
- (?<!\w)microsoft[/\\]windows[/\\]start\smenu[/\\]programs[/\\]startup[/\\]
- (?<!\w)thumbs\.db$
# User Behaviour (Unix)
- (?<!\w)etc[/\\]hosts
- (?<!\w)etc[/\\]passwd
- (?<!\w)etc[/\\]shadow
- (?<!\w)system[/\\]library[/\\]startupitems
EventHints:
- \.evtx$
EventSearchPatterns:
- .+
RegistryHints:
- (?<!\w)system32[/\\].*[/\\]sam$
- (?<!\w)system32[/\\].*[/\\]security$
- (?<!\w)system32[/\\].*[/\\]software$
- (?<!\w)system32[/\\].*[/\\]system$
- (?<!\w)users[/\\].*[/\\]ntuser\.dat$
- (?<!\w)users[/\\].*[/\\]usrclass\.dat$
RegistrySearchPatterns:
# Basic System Information
- (?<!\w)Control[/\\]Computername
- (?<!\w)Software[/\\]Microsoft[/\\]Windows NT[/\\]CurrentVersion
- (?<!\w)Control[/\\]TimeZoneInformation
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Uninstall
- (?<!\w)Enum[/\\]USBSTOR
- (?<!\w)System[/\\]MountedDevices
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Explorer[/\\]MountPoints2
- (?<!\w)Services[/\\]Tcpip[/\\]Parameters[/\\]Interfaces
- (?<!\w)Software[/\\]Microsoft[/\\]Windows NT[/\\]CurrentVersion[/\\]NetworkList[/\\]Profiles
- (?<!\w)Services[/\\]LanmanServer[/\\]Shares
- (?<!\w)Services[/\\]SharedAccess[/\\]Parameters[/\\]FirewallPolicy
# User and Security Information
- (?<!\w)Security[/\\]Policy
- (?<!\w)Software[/\\]Microsoft[/\\]Windows NT[/\\]CurrentVersion[/\\]ProfileList
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Group Policy[/\\].*[/\\]GroupMembership
- (?<!\w)Control[/\\]Session Manager[/\\]AppCompatCache[/\\]AppCompatCache
- (?<!\w)Control[/\\]Session Manager[/\\]AppCompatibility[/\\]AppCompatCache
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Run
- (?<!\w)Software[/\\]Microsoft[/\\]ActiveSetup[/\\]Installed Components
- (?<!\w)Control[/\\]Lsa[/\\]Authentication Packages
- (?<!\w)Control[/\\]Lsa[/\\]Notification Packages
- (?<!\w)Control[/\\]Lsa[/\\]Security Packages
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Explorer[/\\]Browser Helper Objects
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Winlogon
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]Shell
- (?<!\w)Software[/\\]Microsoft[/\\]Windows[/\\]CurrentVersion[/\\]Explorer[/\\]
- (?<!\w)Software[/\\]Microsoft[/\\]Internet Explorer[/\\]Typed
- (?<!\w)Software[/\\]Microsoft[/\\]Terminal Server Client
